### ISSUE TITLE
Reward script

### ISSUE THREAD

**Issue by danielhyuuga** [emrahayanoglu/Node.js--Socket.io-and-Express-based-Multiplayer-Bingo-Game#1]
I would like to add reward system in your bingo script, which part of the codes on what file should I add the reward system?

**Comment by Charmand3r** [comment]
How do i use this?

**Comment by emrahayanoglu** [comment]
sorry for the lateness...

You can check the code within [game model](https://github.com/emrahayanoglu/Node.js--Socket.io-and-Express-based-Multiplayer-Bingo-Game/blob/master/models/game.js),

Most of the game logic is written into the model codes.
