### ISSUE TITLE
How to upload to a website

### ISSUE THREAD

**Issue by Charmand3r** [emrahayanoglu/Node.js--Socket.io-and-Express-based-Multiplayer-Bingo-Game#3]
Can you please help me?

**Comment by emrahayanoglu** [comment]
Please, google it with the following keyword: "node.js socket.io deploy on server".

It is a general question about deployment of the node.js projects. You don't need to do something special rather than the deployment on the server.

**Comment by robel32** [comment]
this doesnt have package.json file how does the "npm i" works to test the code
